- message:
    name: ResumableUploadingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
      - name: uploadSessionUrl
        type: string
        index: 2
      - name: totalBytes
        type: number
        index: 3
- message:
    name: UploadingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
- message:
    name: FormattingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
- message:
    name: MediaProcessingData
    fields:
      - name: uploading
        type: ResumableUploadingState
        index: 1
      - name: formatting
        type: FormattingState
        index: 2
- message:
    name: SubtitleProcessingData
    fields:
      - name: uploading
        type: UploadingState
        index: 1
      - name: formatting
        type: FormattingState
        index: 2
- message:
    name: ProcessingData
    fields:
      - name: media
        type: MediaProcessingData
        index: 1
      - name: subtitle
        type: SubtitleProcessingData
        index: 2
      - name: lastFailures
        type: FailureReason
        import: ./failure_reason
        isArray: true
        index: 3
- message:
    name: VideoTrackData
    fields:
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 1
      - name: durationSec
        type: number
        index: 2
      - name: resolution # E.g. 1280x720
        type: string
        index: 3
      - name: totalBytes
        type: number
        index: 4
- message:
    name: VideoTrack
    fields:
      - name: data # nullable
        type: VideoTrackData
        index: 1
      - name: toAdd # One of add, remove can be set.
        type: VideoTrackData
        index: 2
      - name: toRemove
        type: boolean
        index: 3
- message:
    name: AudioTrackData
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 3
      - name: totalBytes
        type: number
        index: 4
- message:
    name: ChangeAudioTrack
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
- message:
    name: AudioTrack
    fields:
      - name: data # nullable
        type: AudioTrackData
        index: 1
      - name: toAdd # One of add, change, remove can be set.
        type: AudioTrackData
        index: 2
      - name: toChange
        type: ChangeAudioTrack
        index: 3
      - name: toRemove
        type: boolean
        index: 4
- message:
    name: SubtitleTrackData
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 3
      - name: totalBytes
        type: number
        index: 4
- message:
    name: ChangeSubtitleTrack
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
- message:
    name: SubtitleTrack
    fields:
      - name: data # nullable
        type: SubtitleTrackData
        index: 1
      - name: toAdd # One of add, change, remove can be set.
        type: SubtitleTrackData
        index: 2
      - name: toChange
        type: ChangeSubtitleTrack
        index: 3
      - name: toRemove
        type: boolean
        index: 4
- message:
    name: VideoContainerData
    fields:
      - name: source # E.g. show
        type: Source
        import: ./source
        index: 1
      - name: r2Dirname # The dir to contain HLS segments.
        type: string
        index: 2
      - name: version # Incremental. Used to handle out-of-order sync. And used as the master playlist filename.
        type: number
        index: 3
      - name: processing # Nullable
        type: ProcessingData
        index: 4
      - name: videoTracks # Non-null
        type: VideoTrack
        isArray: true
        index: 5
      - name: audioTracks # Non-null
        type: AudioTrack
        isArray: true
        index: 6
      - name: subtitleTracks #Non-null
        type: SubtitleTrack
        isArray: true
        index: 7
- spannerDatabase:
    name: VideoDatabase
    tables:
      - name: VideoContainer
        columns:
          - name: containerId
            type: string
          - name: data
            type: VideoContainerData
        primaryKeys:
          - containerId
      - name: GcsFile
        columns:
          - name: filename
            type: string
            index: 1
        primaryKeys:
          - filename
      - name: R2Key
        columns:
          - name: key # Fully qualified dirname or filename
            type: string
            index: 1
        primaryKeys:
          - key
      - name: VideoContainerSyncingTask
        columns:
          - name: containerId
            type: string
          - name: version
            type: float64
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - version
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: SyncingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: MediaFormattingTask
        columns:
          - name: containerId
            type: string
          - name: gcsFilename
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - gcsFilename
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: MediaFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: SubtitleFormattingTask
        columns:
          - name: containerId
            type: string
          - name: gcsFilename
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - gcsFilename
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: SubtitleFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: GcsFileCleanupTask
        columns:
          - name: filename
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - filename
        indexes:
          - name: GcsFileCleanupByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: R2KeyCleanupTask
        columns:
          - name: key
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - key
        indexes:
          - name: R2KeyCleanupByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
    inserts:
      - name: InsertVideoContainer
        table: VideoContainer
        setColumns:
          - containerId
          - data
      - name: InsertGcsFile
        table: GcsFile
        setColumns:
          - filename
      - name: InsertR2Key
        table: R2Key
        setColumns:
          - key
      - name: InsertVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        setColumns:
          - containerId
          - version
          - executionTimestamp
          - createdTimestamp
      - name: InsertMediaFormattingTask
        table: MediaFormattingTask
        setColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
          - createdTimestamp
      - name: InsertSubtitleFormattingTask
        table: SubtitleFormattingTask
        setColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
          - createdTimestamp
      - name: InsertGcsFileCleanupTask
        table: GcsFileCleanupTask
        setColumns:
          - filename
          - executionTimestamp
          - createdTimestamp
      - name: InsertR2KeyCleanupTask
        table: R2KeyCleanupTask
        setColumns:
          - key
          - executionTimestamp
          - createdTimestamp
    updates:
      - name: UpdateVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
        setColumns:
          - data
      - name: DelayVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
        setColumns:
          - executionTimestamp
      - name: DelayMediaFormattingTask
        table: MediaFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
        setColumns:
          - executionTimestamp
      - name: DelaySubtitleFormattingTask
        table: SubtitleFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
        setColumns:
          - executionTimestamp
      - name: DelayGcsFileCleanupTask
        table: GcsFileCleanupTask
        where:
          op: =
          leftColumn: filename
        setColumns:
          - executionTimestamp
      - name: DelayR2KeyCleanupTask
        table: R2KeyCleanupTask
        where:
          op: =
          leftColumn: key
        setColumns:
          - executionTimestamp
    deletes:
      - name: DeleteVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
      - name: DeleteGcsFile
        table: GcsFile
        where:
          op: =
          leftColumn: filename
      - name: DeleteR2Key
        table: R2Key
        where:
          op: =
          leftColumn: key
      - name: DeleteVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
      - name: DeleteMediaFormattingTask
        table: MediaFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
      - name: DeleteSubtitleFormattingTask
        table: SubtitleFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
      - name: DeleteGcsFileCleanupTask
        table: GcsFileCleanupTask
        where:
          op: =
          leftColumn: filename
      - name: DeleteR2KeyCleanupTask
        table: R2KeyCleanupTask
        where:
          op: =
          leftColumn: key
    selects:
      - name: GetVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - data
      - name: CheckGcsFile
        table: GcsFile
        where:
          op: =
          leftColumn: filename
        getColumns:
          - filename
      - name: CheckR2Key
        table: R2Key
        where:
          op: =
          leftColumn: key
        getColumns:
          - key
      - name: GetVideoContainerSyncingTasks
        table: VideoContainerSyncingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - version
          - executionTimestamp
      - name: GetMediaFormattingTasks
        table: MediaFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
      - name: GetSubtitleFormattingTasks
        table: SubtitleFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
      - name: GetGcsFileCleanupTasks
        table: GcsFileCleanupTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - filename
          - executionTimestamp
      - name: GetR2KeyCleanupTasks
        table: R2KeyCleanupTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - key
          - executionTimestamp
    outputDdl: ./db/ddl
    outputSql: ./db/sql
