- kind: Message
  name: ResumableUploadingState
  fields:
    - name: gcsFilename
      type: string
      index: 1
    - name: uploadSessionUrl
      type: string
      index: 2
    - name: contentLength
      type: number
      index: 3
    - name: contentType
      type: string
      index: 4
- kind: Message
  name: FormattingState
  fields:
    - name: gcsFilename
      type: string
      index: 1
- kind: Message
  name: ProcessingState
  fields:
    - name: uploading
      type: ResumableUploadingState
      index: 1
    - name: formatting
      type: FormattingState
      index: 2
- kind: Message
  name: OneOfProcessingState
  fields:
    - name: media
      type: ProcessingState
      index: 1
    - name: subtitle
      type: ProcessingState
      index: 2
- kind: Message
  name: VideoTrackData
  fields:
    - name: durationSec
      type: number
      index: 1
    - name: resolution # E.g. 1280x720
      type: string
      index: 2
    - name: totalBytes
      type: number
      index: 3
- kind: Message
  name: VideoTrackDataStaging
  fields:
    - name: toAdd
      type: VideoTrackData
      index: 1
    - name: toDelete
      type: boolean
      index: 2
- kind: Message
  name: VideoTrack
  fields:
    - name: r2TrackDirname # The dir that contains HLS segments for a track.
      type: string
      index: 1
    - name: committed
      type: VideoTrackData
      index: 2
    - name: staging # Nullable
      type: VideoTrackDataStaging
      index: 3
- kind: Message
  name: AudioTrackData
  fields:
    - name: name
      type: string
      index: 1
    - name: isDefault
      type: boolean
      index: 2
    - name: totalBytes
      type: number
      index: 3
- kind: Message
  name: AudioTrackDataStaging
  fields:
    - name: toAdd
      type: AudioTrackData
      index: 1
    - name: toDelete
      type: boolean
      index: 2
- kind: Message
  name: AudioTrack
  fields:
    - name: r2TrackDirname # The dir that contains HLS segments for a track.
      type: string
      index: 1
    - name: committed
      type: AudioTrackData
      index: 2
    - name: staging # Nullable
      type: AudioTrackDataStaging
      index: 3
- kind: Message
  name: SubtitleTrackData
  fields:
    - name: name
      type: string
      index: 1
    - name: isDefault
      type: boolean
      index: 2
    - name: totalBytes
      type: number
      index: 3
- kind: Message
  name: SubtitleTrackDataStaging
  fields:
    - name: toAdd
      type: SubtitleTrackData
      index: 1
    - name: toDelete
      type: boolean
      index: 2
- kind: Message
  name: SubtitleTrack
  fields:
    - name: r2TrackDirname # The dir that contains HLS segments for a track.
      type: string
      index: 1
    - name: committed
      type: SubtitleTrackData
      index: 2
    - name: staging # Nullable
      type: SubtitleTrackDataStaging
      index: 3
- kind: Message
  name: WritingToFileState
  fields:
    - name: version
      type: number
      index: 1
    - name: r2FilenamesToDelete
      type: string
      isArray: true
      index: 2
    - name: r2DirnamesToDelete
      type: string
      isArray: true
      index: 3
- kind: Message
  name: SyncingState
  fields:
    - name: version
      type: number
      index: 1
    - name: r2Filename
      type: string
      index: 2
    - name: r2FilenamesToDelete
      type: string
      isArray: true
      index: 3
    - name: r2DirnamesToDelete
      type: string
      isArray: true
      index: 4
- kind: Message
  name: SyncedState
  fields:
    - name: version
      type: number
      index: 1
    - name: r2Filename
      type: string
      index: 2
- kind: Message
  name: MasterPlaylistState
  fields:
    - name: writingToFile
      type: WritingToFileState
      index: 1
    - name: syncing
      type: SyncingState
      index: 2
    - name: synced
      type: SyncedState
      index: 3
- kind: Message
  name: VideoContainer
  fields:
    - name: r2RootDirname # The root dir to contain all HLS segments.
      type: string
      index: 1
    - name: masterPlaylist
      type: MasterPlaylistState
      index: 2
    - name: processing # Nullable
      type: OneOfProcessingState
      index: 3
    - name: lastProcessingFailures # Non-null
      type: ProcessingFailureReason
      import: "@phading/video_service_interface/node/processing_failure_reason"
      isArray: true
      index: 4
    - name: videoTracks # Non-null
      type: VideoTrack
      isArray: true
      index: 5
    - name: audioTracks # Non-null
      type: AudioTrack
      isArray: true
      index: 6
    - name: subtitleTracks # Non-null
      type: SubtitleTrack
      isArray: true
      index: 7
- kind: Message
  name: UploadedRecordingTaskPayload
  fields:
    - name: accountId
      type: string
      index: 1
    - name: totalBytes
      type: number
      index: 2
- kind: Message
  name: StorageStartRecordingTaskPayload
  fields:
    - name: accountId
      type: string
      index: 1
    - name: totalBytes
      type: number
      index: 2
    - name: startTimeMs
      type: number
      index: 3
- kind: Message
  name: StorageEndRecordingTaskPayload
  fields:
    - name: accountId
      type: string
      index: 1
    - name: endTimeMs
      type: number
      index: 2
- kind: SpannerDatabase
  name: VideoDatabase
  tables:
    - kind: Table
      name: VideoContainer
      columns:
        - name: containerId
          type: string
        - name: seasonId
          type: string
          nullable: true
        - name: episodeId
          type: string
          nullable: true
        - name: accountId # Owner
          type: string
          nullable: true
        - name: data
          type: VideoContainer
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - containerId
      insert: InsertVideoContainer
      delete: DeleteVideoContainer
      get: GetVideoContainer
    - kind: Table
      name: GcsFile
      columns:
        - name: filename
          type: string
      primaryKeys:
        - filename
      insert: InsertGcsFile
      delete: DeleteGcsFile
      get: GetGcsFile
    - kind: Table
      name: R2Key
      columns:
        - name: key
          type: string
      primaryKeys:
        - key
      insert: InsertR2Key
      delete: DeleteR2Key
      get: GetR2Key
    - kind: TaskTable
      name: VideoContainerWritingToFileTask
      columns:
        - name: containerId
          type: string
        - name: version
          type: float64
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - containerId
        - version
      executionTimeIndex: WritingToFileByExecutionTime
      insert: InsertVideoContainerWritingToFileTask
      delete: DeleteVideoContainerWritingToFileTask
      get: GetVideoContainerWritingToFileTask
      listPendingTasks: ListPendingVideoContainerWritingToFileTasks
      getMetadata: GetVideoContainerWritingToFileTaskMetadata
      updateMetadata: UpdateVideoContainerWritingToFileTaskMetadata
    - kind: TaskTable
      name: VideoContainerSyncingTask
      columns:
        - name: containerId
          type: string
        - name: version
          type: float64
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - containerId
        - version
      executionTimeIndex: SyncingByExecutionTime
      insert: InsertVideoContainerSyncingTask
      delete: DeleteVideoContainerSyncingTask
      get: GetVideoContainerSyncingTask
      listPendingTasks: ListPendingVideoContainerSyncingTasks
      getMetadata: GetVideoContainerSyncingTaskMetadata
      updateMetadata: UpdateVideoContainerSyncingTaskMetadata
    - kind: TaskTable
      name: UploadedRecordingTask
      columns:
        - name: gcsFilename
          type: string
        - name: payload
          type: UploadedRecordingTaskPayload
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - gcsFilename
      executionTimeIndex: UploadedRecordingByExecutionTime
      insert: InsertUploadedRecordingTask
      delete: DeleteUploadedRecordingTask
      get: GetUploadedRecordingTask
      listPendingTasks: ListPendingUploadedRecordingTasks
      getMetadata: GetUploadedRecordingTaskMetadata
      updateMetadata: UpdateUploadedRecordingTaskMetadata
    - kind: TaskTable
      name: MediaFormattingTask
      columns:
        - name: containerId
          type: string
        - name: gcsFilename
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - containerId
        - gcsFilename
      executionTimeIndex: MediaFormattingByExecutionTime
      insert: InsertMediaFormattingTask
      delete: DeleteMediaFormattingTask
      get: GetMediaFormattingTask
      listPendingTasks: ListPendingMediaFormattingTasks
      getMetadata: GetMediaFormattingTaskMetadata
      updateMetadata: UpdateMediaFormattingTaskMetadata
    - kind: TaskTable
      name: SubtitleFormattingTask
      columns:
        - name: containerId
          type: string
        - name: gcsFilename
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - containerId
        - gcsFilename
      executionTimeIndex: SubtitleFormattingByExecutionTime
      insert: InsertSubtitleFormattingTask
      delete: DeleteSubtitleFormattingTask
      get: GetSubtitleFormattingTask
      listPendingTasks: ListPendingSubtitleFormattingTasks
      getMetadata: GetSubtitleFormattingTaskMetadata
      updateMetadata: UpdateSubtitleFormattingTaskMetadata
    - kind: TaskTable
      name: StorageStartRecordingTask
      columns:
        - name: r2Dirname
          type: string
        - name: payload
          type: StorageStartRecordingTaskPayload
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - r2Dirname
      executionTimeIndex: StorageStartRecordingByExecutionTime
      insert: InsertStorageStartRecordingTask
      delete: DeleteStorageStartRecordingTask
      get: GetStorageStartRecordingTask
      listPendingTasks: ListPendingStorageStartRecordingTasks
      getMetadata: GetStorageStartRecordingTaskMetadata
      updateMetadata: UpdateStorageStartRecordingTaskMetadata
    - kind: TaskTable
      name: StorageEndRecordingTask
      columns:
        - name: r2Dirname
          type: string
        - name: payload
          type: StorageEndRecordingTaskPayload
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - r2Dirname
      executionTimeIndex: StorageEndRecordingByExecutionTime
      insert: InsertStorageEndRecordingTask
      delete: DeleteStorageEndRecordingTask
      get: GetStorageEndRecordingTask
      listPendingTasks: ListPendingStorageEndRecordingTasks
      getMetadata: GetStorageEndRecordingTaskMetadata
      updateMetadata: UpdateStorageEndRecordingTaskMetadata
    - kind: TaskTable
      name: GcsFileDeletingTask
      columns:
        - name: filename
          type: string
        - name: uploadSessionUrl
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - filename
      executionTimeIndex: GcsFileDeleteByExecutionTime
      insert: InsertGcsFileDeletingTask
      delete: DeleteGcsFileDeletingTask
      get: GetGcsFileDeletingTask
      listPendingTasks: ListPendingGcsFileDeletingTasks
      getMetadata: GetGcsFileDeletingTaskMetadata
      updateMetadata: UpdateGcsFileDeletingTaskMetadata
    - kind: TaskTable
      name: R2KeyDeletingTask
      columns:
        - name: key
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - key
      executionTimeIndex: R2KeyDeleteByExecutionTime
      insert: InsertR2KeyDeletingTask
      delete: DeleteR2KeyDeletingTask
      get: GetR2KeyDeletingTask
      listPendingTasks: ListPendingR2KeyDeletingTasks
      getMetadata: GetR2KeyDeletingTaskMetadata
      updateMetadata: UpdateR2KeyDeletingTaskMetadata
  updates:
    - name: UpdateVideoContainer
      table: VideoContainer
      where:
        op: =
        lColumn: containerId
      set:
        - data
  outputDdl: ./db/ddl
  outputSql: ./db/sql
