- message:
    name: ResumableUploadingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
      - name: uploadSessionUrl
        type: string
        index: 2
      - name: contentLength
        type: number
        index: 3
      - name: contentType
        type: string
        index: 4
- message:
    name: FormattingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
- message:
    name: ProcessingState
    fields:
      - name: uploading
        type: ResumableUploadingState
        index: 1
      - name: formatting
        type: FormattingState
        index: 2
- message:
    name: OneOfProcessingState
    fields:
      - name: media
        type: ProcessingState
        index: 1
      - name: subtitle
        type: ProcessingState
        index: 2
- message:
    name: VideoTrackData
    fields:
      - name: durationSec
        type: number
        index: 1
      - name: resolution # E.g. 1280x720
        type: string
        index: 2
      - name: totalBytes
        type: number
        index: 3
- message:
    name: VideoTrackDataStaging
    fields:
      - name: toAdd
        type: VideoTrackData
        index: 1
      - name: toDelete
        type: boolean
        index: 2
- message:
    name: VideoTrack
    fields:
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 1
      - name: committed
        type: VideoTrackData
        index: 2
      - name: staging # Nullable
        type: VideoTrackDataStaging
        index: 3
- message:
    name: AudioTrackData
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
      - name: totalBytes
        type: number
        index: 3
- message:
    name: AudioTrackDataStaging
    fields:
      - name: toAdd
        type: AudioTrackData
        index: 1
      - name: toDelete
        type: boolean
        index: 2
- message:
    name: AudioTrack
    fields:
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 1
      - name: committed
        type: AudioTrackData
        index: 2
      - name: staging # Nullable
        type: AudioTrackDataStaging
        index: 3
- message:
    name: SubtitleTrackData
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
      - name: totalBytes
        type: number
        index: 3
- message:
    name: SubtitleTrackDataStaging
    fields:
      - name: toAdd
        type: SubtitleTrackData
        index: 1
      - name: toDelete
        type: boolean
        index: 2
- message:
    name: SubtitleTrack
    fields:
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 1
      - name: committed
        type: SubtitleTrackData
        index: 2
      - name: staging # Nullable
        type: SubtitleTrackDataStaging
        index: 3
- message:
    name: WritingToFileState
    fields:
      - name: version
        type: number
        index: 1
      - name: r2FilenamesToDelete
        type: string
        isArray: true
        index: 2
      - name: r2DirnamesToDelete
        type: string
        isArray: true
        index: 3
- message:
    name: SyncingState
    fields:
      - name: version
        type: number
        index: 1
      - name: r2Filename
        type: string
        index: 2
      - name: r2FilenamesToDelete
        type: string
        isArray: true
        index: 3
      - name: r2DirnamesToDelete
        type: string
        isArray: true
        index: 4
- message:
    name: SyncedState
    fields:
      - name: version
        type: number
        index: 1
      - name: r2Filename
        type: string
        index: 2
- message:
    name: MasterPlaylistState
    fields:
      - name: writingToFile
        type: WritingToFileState
        index: 1
      - name: syncing
        type: SyncingState
        index: 2
      - name: synced
        type: SyncedState
        index: 3
- message:
    name: VideoContainerData
    fields:
      - name: seasonId
        type: string
        index: 1
      - name: episodeId
        type: string
        index: 2
      - name: r2RootDirname # The root dir to contain all HLS segments.
        type: string
        index: 3
      - name: masterPlaylist
        type: MasterPlaylistState
        index: 4
      - name: processing # Nullable
        type: OneOfProcessingState
        index: 5
      - name: lastProcessingFailures # Non-null
        type: ProcessingFailureReason
        import: "@phading/video_service_interface/node/processing_failure_reason"
        isArray: true
        index: 6
      - name: videoTracks # Non-null
        type: VideoTrack
        isArray: true
        index: 7
      - name: audioTracks # Non-null
        type: AudioTrack
        isArray: true
        index: 8
      - name: subtitleTracks # Non-null
        type: SubtitleTrack
        isArray: true
        index: 9
- message:
    name: GcsFileDeleteTaskPayload
    fields:
      - name: uploadSessionUrl
        type: string
        index: 1
- spannerDatabase:
    name: VideoDatabase
    tables:
      - name: VideoContainer
        columns:
          - name: containerId
            type: string
          - name: data
            type: VideoContainerData
        primaryKeys:
          - containerId
      - name: GcsFile
        columns:
          - name: filename
            type: string
            index: 1
        primaryKeys:
          - filename
      - name: R2Key
        columns:
          - name: key # Fully qualified dirname or filename
            type: string
            index: 1
        primaryKeys:
          - key
      - name: VideoContainerWritingToFileTask
        columns:
          - name: containerId
            type: string
          - name: version
            type: float64
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - version
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: GeneratingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: VideoContainerSyncingTask
        columns:
          - name: containerId
            type: string
          - name: version
            type: float64
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - version
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: SyncingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: MediaFormattingTask
        columns:
          - name: containerId
            type: string
          - name: gcsFilename
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - gcsFilename
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: MediaFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: SubtitleFormattingTask
        columns:
          - name: containerId
            type: string
          - name: gcsFilename
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - gcsFilename
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: SubtitleFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: GcsFileDeleteTask
        columns:
          - name: filename
            type: string
          - name: payload
            type: GcsFileDeleteTaskPayload
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - filename
        indexes:
          - name: GcsFileDeleteByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: R2KeyDeleteTask
        columns:
          - name: key
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - key
        indexes:
          - name: R2KeyDeleteByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
    inserts:
      - name: InsertVideoContainer
        table: VideoContainer
        setColumns:
          - containerId
          - data
      - name: InsertGcsFile
        table: GcsFile
        setColumns:
          - filename
      - name: InsertR2Key
        table: R2Key
        setColumns:
          - key
      - name: InsertVideoContainerWritingToFileTask
        table: VideoContainerWritingToFileTask
        setColumns:
          - containerId
          - version
          - executionTimestamp
          - createdTimestamp
      - name: InsertVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        setColumns:
          - containerId
          - version
          - executionTimestamp
          - createdTimestamp
      - name: InsertMediaFormattingTask
        table: MediaFormattingTask
        setColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
          - createdTimestamp
      - name: InsertSubtitleFormattingTask
        table: SubtitleFormattingTask
        setColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
          - createdTimestamp
      - name: InsertGcsFileDeleteTask
        table: GcsFileDeleteTask
        setColumns:
          - filename
          - payload
          - executionTimestamp
          - createdTimestamp
      - name: InsertR2KeyDeleteTask
        table: R2KeyDeleteTask
        setColumns:
          - key
          - executionTimestamp
          - createdTimestamp
    updates:
      - name: UpdateVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
        setColumns:
          - data
      - name: UpdateVideoContainerWritingToFileTask
        table: VideoContainerWritingToFileTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
        setColumns:
          - executionTimestamp
      - name: UpdateVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
        setColumns:
          - executionTimestamp
      - name: UpdateMediaFormattingTask
        table: MediaFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
        setColumns:
          - executionTimestamp
      - name: UpdateSubtitleFormattingTask
        table: SubtitleFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
        setColumns:
          - executionTimestamp
      - name: UpdateGcsFileDeleteTask
        table: GcsFileDeleteTask
        where:
          op: =
          leftColumn: filename
        setColumns:
          - executionTimestamp
      - name: UpdateR2KeyDeleteTask
        table: R2KeyDeleteTask
        where:
          op: =
          leftColumn: key
        setColumns:
          - executionTimestamp
    deletes:
      - name: DeleteVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
      - name: DeleteGcsFile
        table: GcsFile
        where:
          op: =
          leftColumn: filename
      - name: DeleteR2Key
        table: R2Key
        where:
          op: =
          leftColumn: key
      - name: DeleteVideoContainerWritingToFileTask
        table: VideoContainerWritingToFileTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
      - name: DeleteVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
      - name: DeleteMediaFormattingTask
        table: MediaFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
      - name: DeleteSubtitleFormattingTask
        table: SubtitleFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: gcsFilename
      - name: DeleteGcsFileDeleteTask
        table: GcsFileDeleteTask
        where:
          op: =
          leftColumn: filename
      - name: DeleteR2KeyDeleteTask
        table: R2KeyDeleteTask
        where:
          op: =
          leftColumn: key
    selects:
      - name: GetVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - data
      - name: CheckGcsFile
        table: GcsFile
        where:
          op: =
          leftColumn: filename
        getColumns:
          - filename
      - name: CheckR2Key
        table: R2Key
        where:
          op: =
          leftColumn: key
        getColumns:
          - key
      - name: ListVideoContainerWritingToFileTasks
        table: VideoContainerWritingToFileTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - version
          - executionTimestamp
      - name: ListVideoContainerSyncingTasks
        table: VideoContainerSyncingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - version
          - executionTimestamp
      - name: ListMediaFormattingTasks
        table: MediaFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
      - name: ListSubtitleFormattingTasks
        table: SubtitleFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - gcsFilename
          - executionTimestamp
      - name: ListGcsFileDeleteTasks
        table: GcsFileDeleteTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - filename
          - payload
          - executionTimestamp
      - name: ListR2KeyDeleteTasks
        table: R2KeyDeleteTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - key
          - executionTimestamp
    outputDdl: ./db/ddl
    outputSql: ./db/sql
