- message:
    name: ResumableUploadingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
      - name: uploadSessionUrl
        type: string
        index: 2
      - name: totalBytes
        type: number
        index: 3
- message:
    name: UploadingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
- message:
    name: FormattingState
    fields:
      - name: gcsFilename
        type: string
        index: 1
- message:
    name: FailureState
    fields:
      - name: reasons
        type: FailureReason
        import: ./failure_reason
        isArray: true
        index: 1
- message:
    name: VideoTrackDoneState
    fields:
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 1
      - name: durationSec
        type: number
        index: 2
      - name: resolution # E.g. 1280x720
        type: string
        index: 3
      - name: totalBytes
        type: number
        index: 4
- message:
    name: DoneState
    fields:
      - name: r2TrackDirname # The dir that contains HLS segments for a track.
        type: string
        index: 1
      - name: totalBytes
        type: number
        index: 2
- message:
    name: VideoTrackData
    fields:
      - name: uploading
        type: ResumableUploadingState
        index: 1
      - name: formatting
        type: FormattingState
        index: 2
      - name: failure
        type: FailureState
        index: 3
      - name: done
        type: VideoTrackDoneState
        index: 4
- message:
    name: AudioTrackData
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
      - name: uploading
        type: ResumableUploadingState
        index: 3
      - name: formatting
        type: FormattingState
        index: 4
      - name: failure
        type: FailureState
        index: 5
      - name: done
        type: DoneState
        index: 6
- message:
    name: SubtitleTrackData
    fields:
      - name: name
        type: string
        index: 1
      - name: isDefault
        type: boolean
        index: 2
      - name: uploading
        type: UploadingState
        index: 3
      - name: formatting
        type: FormattingState
        index: 4
      - name: failure
        type: FailureState
        index: 5
      - name: done
        type: DoneState
        index: 6
- message:
    name: VideoContainerData
    fields:
      - name: source # E.g. show
        type: Source
        import: ./source
        index: 1
      - name: r2Dirname # The dir to contain HLS segments.
        type: string
        index: 2
      - name: version # Incremental. Used to handle out-of-order sync. And used as the master playlist filename.
        type: number
        index: 3
      - name: totalBytes
        type: number
        index: 4
- spannerDatabase:
    name: VideoDatabase
    tables:
      - name: VideoContainer
        columns:
          - name: containerId
            type: string
          - name: data
            type: VideoContainerData
        primaryKeys:
          - containerId
      - name: VideoTrack
        columns:
          - name: containerId
            type: string
          - name: videoId
            type: string
          - name: data
            type: VideoTrackData
        primaryKeys:
          - containerId
          - videoId
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
      - name: AudioTrack
        columns:
          - name: containerId
            type: string
          - name: audioId
            type: string
          - name: data
            type: AudioTrackData
        primaryKeys:
          - containerId
          - audioId
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
      - name: SubtitleTrack
        columns:
          - name: containerId
            type: string
          - name: subtitleId
            type: string
          - name: data
            type: SubtitleTrackData
        primaryKeys:
          - containerId
          - subtitleId
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
      - name: GcsFile
        columns:
          - name: filename
            type: string
            index: 1
        primaryKeys:
          - filename
      - name: R2Key
        columns:
          - name: key # Fully qualified dirname or filename
            type: string
            index: 1
        primaryKeys:
          - key
      - name: VideoContainerSyncingTask
        columns:
          - name: containerId
            type: string
          - name: version
            type: float64
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - version
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: SyncingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: VideoFormattingTask
        columns:
          - name: containerId
            type: string
          - name: videoId
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - videoId
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: VideoFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: AudioFormattingTask
        columns:
          - name: containerId
            type: string
          - name: audioId
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - audioId
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: AudioFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: SubtitleFormattingTask
        columns:
          - name: containerId
            type: string
          - name: subtitleId
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - containerId
          - subtitleId
        interleave:
          parentTable: VideoContainer
          cascadeOnDelete: true
        indexes:
          - name: SubtitleFormattingByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: GcsFileCleanupTask
        columns:
          - name: filename
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - filename
        indexes:
          - name: GcsFileCleanupByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
      - name: R2KeyCleanupTask
        columns:
          - name: key
            type: string
          - name: executionTimestamp
            type: timestamp
          - name: createdTimestamp
            type: timestamp
        primaryKeys:
          - key
        indexes:
          - name: R2KeyCleanupByExecutionTime
            columns:
              - name: executionTimestamp
                desc: true
    inserts:
      - name: InsertVideoContainer
        table: VideoContainer
        setColumns:
          - containerId
          - data
      - name: InsertVideoTrack
        table: VideoTrack
        setColumns:
          - containerId
          - videoId
          - data
      - name: InsertAudioTrack
        table: AudioTrack
        setColumns:
          - containerId
          - audioId
          - data
      - name: InsertSubtitleTrack
        table: SubtitleTrack
        setColumns:
          - containerId
          - subtitleId
          - data
      - name: InsertGcsFile
        table: GcsFile
        setColumns:
          - filename
      - name: InsertR2Key
        table: R2Key
        setColumns:
          - key
      - name: InsertVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        setColumns:
          - containerId
          - version
          - executionTimestamp
          - createdTimestamp
      - name: InsertVideoFormattingTask
        table: VideoFormattingTask
        setColumns:
          - containerId
          - videoId
          - executionTimestamp
          - createdTimestamp
      - name: InsertGcsFileCleanupTask
        table: GcsFileCleanupTask
        setColumns:
          - filename
          - executionTimestamp
          - createdTimestamp
      - name: InsertR2KeyCleanupTask
        table: R2KeyCleanupTask
        setColumns:
          - key
          - executionTimestamp
          - createdTimestamp
    updates:
      - name: UpdateVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
        setColumns:
          - data
      - name: UpdateVideoTrack
        table: VideoTrack
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: videoId
        setColumns:
          - data
      - name: DelayVideoFormattingTask
        table: VideoFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: videoId
        setColumns:
          - executionTimestamp
      - name: DelayR2KeyCleanupTask
        table: R2KeyCleanupTask
        where:
          op: =
          leftColumn: key
        setColumns:
          - executionTimestamp
    deletes:
      - name: DeleteVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
      - name: DeleteVideoTrack
        table: VideoTrack
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: videoId
      - name: DeleteR2Key
        table: R2Key
        where:
          op: =
          leftColumn: key
      - name: DeleteVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: version
      - name: DeleteVideoFormattingTask
        table: VideoFormattingTask
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: videoId
      - name: DeleteGcsFileCleanupTask
        table: GcsFileCleanupTask
        where:
          op: =
          leftColumn: filename
      - name: DeleteR2KeyCleanupTask
        table: R2KeyCleanupTask
        where:
          op: =
          leftColumn: key
    selects:
      - name: GetVideoContainer
        table: VideoContainer
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - data
      - name: GetAllVideoTracks
        table: VideoTrack
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - videoId
          - data
      - name: GetVideoTrack
        table: VideoTrack
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: videoId
        getColumns:
          - data
      - name: GetAllAudioTracks
        table: AudioTrack
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - audioId
          - data
      - name: GetAudioTrack
        table: AudioTrack
        where:
          op: AND
          exps:
            - op: =
              leftColumn: containerId
            - op: =
              leftColumn: audioId
        getColumns:
          - data
      - name: GetAllSubtitleTracks
        table: SubtitleTrack
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - subtitleId
          - data
      - name: CheckR2Key
        table: R2Key
        where:
          op: =
          leftColumn: key
        getColumns:
          - key
      - name: CheckVideoContainerSyncingTask
        table: VideoContainerSyncingTask
        where:
          op: =
          leftColumn: containerId
        getColumns:
          - version
      - name: GetVideoContainerSyncingTasks
        table: VideoContainerSyncingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - version
          - executionTimestamp
      - name: GetVideoFormattingTasks
        table: VideoFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - videoId
          - executionTimestamp
      - name: GetAudioFormattingTasks
        table: AudioFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - audioId
          - executionTimestamp
      - name: GetSubtitleFormattingTasks
        table: SubtitleFormattingTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - containerId
          - subtitleId
          - executionTimestamp
      - name: GetGcsFileCleanupTasks
        table: GcsFileCleanupTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - filename
          - executionTimestamp
      - name: GetR2KeyCleanupTasks
        table: R2KeyCleanupTask
        where:
          op: <
          leftColumn: executionTimestamp
        orderBy:
          - column: executionTimestamp
            desc: true
        getColumns:
          - key
          - executionTimestamp
    outputDdl: ./db/ddl
    outputSql: ./db/sql
